### ISSUE TITLE
Visible separation between sidebar and shelf

### ISSUE THREAD

**Issue by sprakash57** [sprakash57/Bookplorer#6]
If you click on any of the books, It reveals more details in a sidebar. But there is no separation visible on the screen. Maybe there should be a vertical line(As per the current theme) between the book shelf (the area where books render) and the sidebar.

**Comment by biswain2309** [comment]
I want to work on this. Could you please assign this issue to me?

**Comment by sprakash57** [comment]
Sure. It contains mostly CSS changes.
